[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
libs = ["contracts/lib"]
remappings = [
    "src:forge-std/=contracts/lib/forge-std/src",
    "src:solady/=contracts/lib/solady/src",
]
via_ir = true
evm_version = "prague"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
